version: '2'
services:
    amachou-app:
        image: amachou
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://amachou-postgresql:5432/amachou
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://amachou-elasticsearch:9200
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=zookeeper
        ports:
            - 8080:8080
    amachou-postgresql:
        extends:
            file: postgresql.yml
            service: amachou-postgresql
    amachou-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: amachou-elasticsearch
    kafka:
        extends:
            file: kafka.yml
            service: kafka
        environment:
            - KAFKA_ADVERTISED_HOST_NAME=kafka
    zookeeper:
        extends:
            file: kafka.yml
            service: zookeeper
